configure checks to make sure EPEL is installed

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -5,9 +5,42 @@
 # the necessary tools installed on your computer.
 ################################################################################
 
-echo "Configure computer so it can build the NAS Encryptor plugin:"
-echo ""
-echo "`basename ${0}` Success."
+export TOP_DIR=$( cd `dirname ${0}` && echo ${PWD} )
+readonly PKG_CONFIGURE_SCRIPT=${TOP_DIR}/PKG/configure
 
+########################################
+# What are we building?
+echo ""
+echo "Configuring the build computer for building the NAS Encryptor."
+echo ""
+
+########################################
+# Initialize some stuff before we start building.
+echo "Initialization:"
+
+readonly LOG=/tmp/`basename ${0}`.log
+echo -n "  Initialize log file (${LOG}) ... "
+rm -f ${LOG} &> /dev/null
+[ $? -ne 0 ] && echo "Unable to delete old log file." && exit 1
+touch ${LOG} &> /dev/null
+[ $? -ne 0 ] && echo "Unable to create empty log file." && exit 1
+echo "Pass."
+echo ""
+
+########################################
+# Locate the configure scripts for each subdirectory.
+echo "Locate configure scripts:"
+echo -n "  PKG build (${PKG_CONFIGURE_SCRIPT}) ... "
+[ ! -f ${PKG_CONFIGURE_SCRIPT} ] && echo "Fail." && exit 1 ; echo "Pass."
+echo ""
+
+########################################
+# The NAS Encryptor package.
+${PKG_CONFIGURE_SCRIPT}
+[ $? -ne 0 ] && exit 1
+echo ""
+
+########################################
+# Done.  Success.
 exit 0
 
